name = "logic"
defaultTargets = ["Logic"]

[leanOptions]
pp.unicode.fun = true

[[require]]
name = "batteries"
scope = "leanprover-community"

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "Logic"
